[package]
name = "x_example"
type = "bin"
authors = ["Vedant Chainani <vedant@zkpersona.xyz>"]
compiler_version = ">=0.1.0"
license = "MIT"

[dependencies]
noir_social_verify = { path = "../../lib" }
zkemail = { tag = "v0.4.2", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
